In [ ]:
# obtain gguf
# read set values from yaml
!set model_url
!set GIT_LFS_SKIP_SMUDGE=1 && git clone $model_url
!set model_name=regex model_url_rfind_slash
!python llama.cpp/convert_hf_to_gguf.py $model_name --outfile ./$model_name+'.gguf'
!llama-quantize $model_name.gguf $model_name+$quantization_type.gguf $quantization_type N=?-1?

In [ ]:
import benchmark
import time
for model_name in ["olmo2_IQ4_XS"]:#,"smolm2-pruned-sparsegpt-q4km"]:
    model_path=f'/mnt/d/Inno/Thesis/out/olmo2/olmo2_IQ4_XS.gguf'
    benchllm=benchmark.BenchLLM('../../llama.cpp/build/bin/llama-server','../../llama.cpp/build/bin/llama-perplexity',model_path)
    time.sleep(10) # wait for previous model free and server to close
    benchllm.start_server()
    time.sleep(150) # wait for model to load
    benchllm.bench() # stop server itself
    benchllm.save_to_file(f'./{model_name}')

In [ ]:
model_path=f'/mnt/d/Inno/Thesis/{model_name}.gguf'
benchllm=benchmark.BenchLLM('../../llama.cpp/bin/llama-server','../../llama.cpp/bin/llama-perplexity',model_path)
time.sleep(10) # wait for previous model free and server to close
benchllm.start_server()

In [1]:
from pathlib import Path 
folder_path=Path("../../out/olmo2")
[str(path.parent) for path in folder_path.rglob("quantize_config.json")] + [str(path) for path in folder_path.rglob("*.gguf")]

['../../out/olmo2/quantized/olmo2_unstructured_wanda_0.2_gptq_4',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.2_gptq_8',
 '../../out/olmo2/quantized/olmo2_gptq_8',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.5_gptq_8',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_gptq_8',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_gptq_4',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.5_gptq_4',
 '../../out/olmo2/quantized/olmo2_gptq_4',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_gptq_4',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_gptq_8',
 '../../out/olmo2/original/olmo2_q16.gguf',
 '../../out/olmo2/pruned/unstructured/wanda/0.2/olmo2_unstructured_wanda_0.2_q16.gguf',
 '../../out/olmo2/pruned/unstructured/wanda/0.5/olmo2_unstructured_wanda_0.5_q16.gguf',
 '../../out/olmo2/pruned/unstructured/sparsegpt/0.2/olmo2_unstructured_sparsegpt_0.2_q16.gguf',
 '../../out/olmo2/pruned/unstructured/sparsegpt/0.5/olmo2_unstructured_sparsegpt_0.5_q16.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.2_llama.cpp_4/olmo2_unstructured_wanda_0.2_IQ4_XS.gguf',
 '../../out/olmo2/quantized/olmo2_llama.cpp_8/olmo2_Q8_0.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_llama.cpp_8/olmo2_unstructured_sparsegpt_0.2_Q8_0.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.5_llama.cpp_8/olmo2_unstructured_wanda_0.5_Q8_0.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_llama.cpp_4/olmo2_unstructured_sparsegpt_0.5_IQ4_XS.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_llama.cpp_4/olmo2_unstructured_sparsegpt_0.2_IQ4_XS.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.2_llama.cpp_8/olmo2_unstructured_wanda_0.2_Q8_0.gguf',
 '../../out/olmo2/quantized/olmo2_llama.cpp_4/olmo2_IQ4_XS.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_wanda_0.5_llama.cpp_4/olmo2_unstructured_wanda_0.5_IQ4_XS.gguf',
 '../../out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_llama.cpp_8/olmo2_unstructured_sparsegpt_0.5_Q8_0.gguf']

In [3]:
import benchmark_client
benchllm=benchmark_client.BenchLLMClient('##','##')
result_df=benchllm.compare_results('../../out/smollm2/benchmark_results/out/smollm2','../../out/smollm2/benchmark_results/out/smollm2/original/smollm2_q16.gguf.json')
# p value is calculated for accuracy with McNemar's test p-value relative to base model
result_df

2026-04-29 16:45:26,565 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-29 16:45:26,615 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/hotpotqa/hotpot_qa/1908d6afbbead072334abe2965f91bd2709910ab/README.md "HTTP/1.1 200 OK"
2026-04-29 16:45:26,790 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/1908d6afbbead072334abe2965f91bd2709910ab/hotpot_qa.py "HTTP/1.1 404 Not Found"
2026-04-29 16:45:27,230 - INFO - HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/hotpotqa/hotpot_qa/hotpotqa/hotpot_qa.py "HTTP/1.1 404 Not Found"
2026-04-29 16:45:27,349 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/1908d6afbbead072334abe2965f91bd2709910ab/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-29 16:45:27,618 - INFO - HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=hotpotqa/hotpot_qa "HTTP/1.1 200 OK"
2026-04-29 16:45:27,793 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/1908d6afbbead072334abe2965f91bd2709910ab/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-29 16:45:27,809 - INFO - 25 json_files: ['../../out/smollm2/benchmark_results/out/smollm2/original/smollm2_q16.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.5_gptq_4.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_gptq_8.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.2_gptq_4.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.5_gptq_8.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.5_gptq_4.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_gptq_4.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.5_gptq_8.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.2_gptq_8.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.2_gptq_4.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.2_gptq_8.json', '../../out/smollm2/benchmark_results/out/smollm2/pruned/unstructured/wanda/0.2/smollm2_unstructured_wanda_0.2_q16.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/pruned/unstructured/wanda/0.5/smollm2_unstructured_wanda_0.5_q16.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/pruned/unstructured/sparsegpt/0.2/smollm2_unstructured_sparsegpt_0.2_q16.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/pruned/unstructured/sparsegpt/0.5/smollm2_unstructured_sparsegpt_0.5_q16.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.5_llama.cpp_4/smollm2_unstructured_sparsegpt_0.5_IQ4_XS.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.2_llama.cpp_8/smollm2_unstructured_sparsegpt_0.2_Q8_0.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.2_llama.cpp_4/smollm2_unstructured_wanda_0.2_IQ4_XS.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.5_llama.cpp_4/smollm2_unstructured_wanda_0.5_IQ4_XS.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.5_llama.cpp_8/smollm2_unstructured_sparsegpt_0.5_Q8_0.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_llama.cpp_8/smollm2_Q8_0.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_llama.cpp_4/smollm2_IQ4_XS.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_sparsegpt_0.2_llama.cpp_4/smollm2_unstructured_sparsegpt_0.2_IQ4_XS.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.2_llama.cpp_8/smollm2_unstructured_wanda_0.2_Q8_0.gguf.json', '../../out/smollm2/benchmark_results/out/smollm2/quantized/smollm2_unstructured_wanda_0.5_llama.cpp_8/smollm2_unstructured_wanda_0.5_Q8_0.gguf.json']

!

,method,accuracy,ppl,prefill,decode,cor->incor,incor->cor,p_value (mcNemar),CI (95%)
0,smollm2_q16.gguf.json,0.30,9.68+-0.50,37.66+-2.20,9.29+-0.68,0.00,0.00,"nan,n=200","nan,nan"
1,smollm2_unstructured_sparsegpt_0.5_gptq_4.json,0.23,38.92+-27.06,46.29+-6.39,24.95+-5.81,0.54,0.24,"0.02,n=200","0.01,0.13"
2,smollm2_gptq_8.json,0.31,22.16+-17.15,56.01+-10.17,19.94+-4.09,0.05,0.08,"0.48,n=200","-0.04,0.02"
3,smollm2_unstructured_wanda_0.2_gptq_4.json,0.32,24.11+-16.05,34.23+-4.05,34.50+-10.82,0.20,0.27,"0.47,n=200","-0.07,0.03"
4,smollm2_unstructured_wanda_0.5_gptq_8.json,0.21,32.94+-21.85,53.19+-9.70,18.50+-4.38,0.58,0.19,"0.00,n=200","0.03,0.14"
5,smollm2_unstructured_wanda_0.5_gptq_4.json,0.26,38.85+-25.40,43.41+-6.01,27.53+-40.47,0.37,0.21,"0.14,n=200","-0.01,0.09"
6,smollm2_gptq_4.json,0.29,23.98+-15.82,44.22+-6.41,29.27+-6.13,0.21,0.17,"0.67,n=200","-0.04,0.06"
7,smollm2_unstructured_sparsegpt_0.5_gptq_8.json,0.21,32.63+-21.32,53.32+-10.01,18.53+-4.29,0.58,0.19,"0.00,n=200","0.03,0.14"
8,smollm2_unstructured_sparsegpt_0.2_gptq_8.json,0.32,21.57+-14.60,50.56+-10.58,18.59+-4.59,0.13,0.17,"0.49,n=200","-0.06,0.03"
9,smollm2_unstructured_sparsegpt_0.2_gptq_4.json,0.30,24.51+-16.43,34.23+-4.05,20.47+-5.56,0.21,0.23,"0.85,n=200","-0.06,0.05"
10,smollm2_unstructured_wanda_0.2_gptq_8.json,0.32,21.26+-14.34,55.10+-10.99,18.78+-4.30,0.16,0.21,"0.53,n=200","-0.06,0.03"
11,smollm2_unstructured_wanda_0.2_q16.gguf.json,0.32,9.85+-0.52,36.54+-2.79,9.00+-0.44,0.14,0.19,"0.51,n=200","-0.06,0.03"
12,smollm2_unstructured_wanda_0.5_q16.gguf.json,0.24,14.97+-0.88,36.53+-2.25,8.92+-0.28,0.45,0.22,"0.06,n=200","-0.00,0.11"
13,smollm2_unstructured_sparsegpt_0.2_q16.gguf.json,0.30,9.94+-0.52,36.95+-2.23,8.87+-0.26,0.15,0.15,"1.00,n=200","-0.04,0.04"
14,smollm2_unstructured_sparsegpt_0.5_q16.gguf.json,0.23,14.69+-0.85,36.97+-2.28,8.98+-0.34,0.53,0.20,"0.01,n=200","0.02,0.13"
15,smollm2_unstructured_sparsegpt_0.5_IQ4_XS.gguf...,0.26,16.35+-0.99,44.21+-2.97,27.07+-2.20,0.41,0.24,"0.12,n=200","-0.01,0.10"
16,smollm2_unstructured_sparsegpt_0.2_Q8_0.gguf.json,0.29,9.95+-0.52,77.24+-6.97,15.73+-0.57,0.19,0.16,"0.65,n=200","-0.03,0.05"
17,smollm2_unstructured_wanda_0.2_IQ4_XS.gguf.json,0.29,10.64+-0.57,43.68+-3.26,26.59+-2.05,0.24,0.22,"0.85,n=200","-0.05,0.06"
18,smollm2_unstructured_wanda_0.5_IQ4_XS.gguf.json,0.26,16.95+-1.02,43.24+-3.29,26.34+-1.70,0.41,0.24,"0.12,n=200","-0.01,0.10"
19,smollm2_unstructured_sparsegpt_0.5_Q8_0.gguf.json,0.24,14.76+-0.85,76.67+-8.44,15.96+-0.65,0.48,0.23,"0.04,n=200","0.00,0.12"
20,smollm2_Q8_0.gguf.json,0.30,9.70+-0.50,76.72+-7.53,16.14+-1.14,0.07,0.07,"1.00,n=200","-0.03,0.03"
21,smollm2_IQ4_XS.gguf.json,0.28,10.54+-0.55,44.16+-2.89,27.14+-2.09,0.29,0.21,"0.45,n=200","-0.03,0.07"
22,smollm2_unstructured_sparsegpt_0.2_IQ4_XS.gguf...,0.29,10.72+-0.57,43.91+-2.80,26.54+-1.75,0.28,0.24,"0.72,n=200","-0.04,0.06"
23,smollm2_unstructured_wanda_0.2_Q8_0.gguf.json,0.32,9.87+-0.52,74.14+-8.96,15.97+-0.74,0.16,0.21,"0.53,n=200","-0.06,0.03"
24,smollm2_unstructured_wanda_0.5_Q8_0.gguf.json,0.26,15.04+-0.87,75.94+-8.55,15.78+-0.54,0.43,0.25,"0.13,n=200","-0.01,0.10"

In [ ]:
benchllm.calc_corr(result_df)

In [2]:
import benchmark_client
benchllm=benchmark_client.BenchLLMClient('##','##')
result_df=benchllm.compare_results('../../out/olmo2/benchmark_results/out/olmo2','../../out/olmo2/benchmark_results/out/olmo2/original/olmo2_q16.gguf.json')
result_df

2026-04-29 16:44:56,713 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-04-29 16:44:56,756 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/hotpotqa/hotpot_qa/1908d6afbbead072334abe2965f91bd2709910ab/README.md "HTTP/1.1 200 OK"
2026-04-29 16:44:56,927 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/1908d6afbbead072334abe2965f91bd2709910ab/hotpot_qa.py "HTTP/1.1 404 Not Found"
2026-04-29 16:44:57,402 - INFO - HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/hotpotqa/hotpot_qa/hotpotqa/hotpot_qa.py "HTTP/1.1 404 Not Found"
2026-04-29 16:44:57,520 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/1908d6afbbead072334abe2965f91bd2709910ab/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-04-29 16:44:57,795 - INFO - HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=hotpotqa/hotpot_qa "HTTP/1.1 200 OK"
2026-04-29 16:44:57,974 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/hotpotqa/hotpot_qa/resolve/1908d6afbbead072334abe2965f91bd2709910ab/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-04-29 16:44:57,992 - INFO - 25 json_files: ['../../out/olmo2/benchmark_results/out/olmo2/original/olmo2_q16.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_gptq_4.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.5_gptq_8.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.2_gptq_8.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_gptq_4.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_gptq_4.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.2_gptq_4.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_gptq_8.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_gptq_8.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_gptq_8.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.5_gptq_4.json', '../../out/olmo2/benchmark_results/out/olmo2/pruned/unstructured/wanda/0.2/olmo2_unstructured_wanda_0.2_q16.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/pruned/unstructured/wanda/0.5/olmo2_unstructured_wanda_0.5_q16.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/pruned/unstructured/sparsegpt/0.2/olmo2_unstructured_sparsegpt_0.2_q16.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/pruned/unstructured/sparsegpt/0.5/olmo2_unstructured_sparsegpt_0.5_q16.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.2_llama.cpp_4/olmo2_unstructured_wanda_0.2_IQ4_XS.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_llama.cpp_8/olmo2_Q8_0.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_llama.cpp_8/olmo2_unstructured_sparsegpt_0.2_Q8_0.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.5_llama.cpp_8/olmo2_unstructured_wanda_0.5_Q8_0.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_llama.cpp_4/olmo2_unstructured_sparsegpt_0.5_IQ4_XS.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.2_llama.cpp_4/olmo2_unstructured_sparsegpt_0.2_IQ4_XS.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.2_llama.cpp_8/olmo2_unstructured_wanda_0.2_Q8_0.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_llama.cpp_4/olmo2_IQ4_XS.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_wanda_0.5_llama.cpp_4/olmo2_unstructured_wanda_0.5_IQ4_XS.gguf.json', '../../out/olmo2/benchmark_results/out/olmo2/quantized/olmo2_unstructured_sparsegpt_0.5_llama.cpp_8/olmo2_unstructured_sparsegpt_0.5_Q8_0.gguf.json']

!

,method,accuracy,ppl,prefill,decode,cor->incor,incor->cor,p_value (mcNemar),CI (95%)
0,olmo2_q16.gguf.json,0.14,13.81+-0.86,58.64+-4.50,12.78+-1.15,0.00,0.00,"nan,n=200","nan,nan"
1,olmo2_unstructured_sparsegpt_0.5_gptq_4.json,0.27,38.57+-23.48,60.89+-6.28,45.24+-10.71,0.22,0.69,"0.00,n=200","-0.19,-0.06"
2,olmo2_unstructured_wanda_0.5_gptq_8.json,0.24,37.66+-21.73,60.85+-10.33,23.48+-8.18,0.35,0.75,"0.01,n=200","-0.17,-0.02"
3,olmo2_unstructured_wanda_0.2_gptq_8.json,0.29,30.68+-17.56,61.85+-9.51,31.27+-7.87,0.21,0.71,"0.00,n=200","-0.22,-0.07"
4,olmo2_gptq_4.json,0.28,24.16+-16.74,63.12+-8.95,25.85+-3.80,0.23,0.72,"0.00,n=200","-0.21,-0.07"
5,olmo2_unstructured_sparsegpt_0.2_gptq_4.json,0.28,33.22+-18.81,70.82+-6.42,30.54+-11.40,0.18,0.66,"0.00,n=200","-0.20,-0.07"
6,olmo2_unstructured_wanda_0.2_gptq_4.json,0.32,24.11+-16.05,53.27+-7.28,59.14+-12.93,0.17,0.72,"0.00,n=200","-0.25,-0.10"
7,olmo2_unstructured_sparsegpt_0.5_gptq_8.json,0.24,37.07+-23.09,60.85+-10.33,23.41+-8.14,0.31,0.71,"0.01,n=200","-0.16,-0.03"
8,olmo2_unstructured_sparsegpt_0.2_gptq_8.json,0.28,31.31+-17.89,68.35+-13.53,29.15+-5.54,0.21,0.70,"0.00,n=200","-0.21,-0.07"
9,olmo2_gptq_8.json,0.14,21.73+-16.54,71.48+-16.22,30.39+-6.31,0.69,0.69,"1.00,n=200","-0.06,0.06"
10,olmo2_unstructured_wanda_0.5_gptq_4.json,0.23,39.83+-22.94,61.11+-8.53,43.25+-10.39,0.37,0.74,"0.02,n=200","-0.15,-0.02"
11,olmo2_unstructured_wanda_0.2_q16.gguf.json,0.31,13.96+-0.85,59.46+-4.21,13.91+-2.05,0.16,0.69,"0.00,n=200","-0.24,-0.09"
12,olmo2_unstructured_wanda_0.5_q16.gguf.json,0.23,17.63+-1.00,58.61+-4.62,13.71+-2.02,0.35,0.72,"0.02,n=200","-0.15,-0.02"
13,olmo2_unstructured_sparsegpt_0.2_q16.gguf.json,0.29,21.16+-1.48,58.68+-4.39,14.18+-2.52,0.17,0.68,"0.00,n=200","-0.22,-0.08"
14,olmo2_unstructured_sparsegpt_0.5_q16.gguf.json,0.27,16.69+-0.95,60.81+-3.47,13.70+-1.83,0.24,0.70,"0.00,n=200","-0.19,-0.06"
15,olmo2_unstructured_wanda_0.2_IQ4_XS.gguf.json,0.28,14.68+-0.87,72.77+-5.16,41.84+-6.98,0.23,0.72,"0.00,n=200","-0.21,-0.07"
16,olmo2_Q8_0.gguf.json,0.14,13.83+-0.86,126.95+-12.85,23.25+-3.03,0.67,0.59,"0.73,n=200","-0.05,0.07"
17,olmo2_unstructured_sparsegpt_0.2_Q8_0.gguf.json,0.28,21.18+-1.48,125.54+-13.72,24.91+-4.40,0.22,0.69,"0.00,n=200","-0.20,-0.06"
18,olmo2_unstructured_wanda_0.5_Q8_0.gguf.json,0.26,17.66+-1.00,126.43+-13.11,25.22+-4.35,0.29,0.73,"0.00,n=200","-0.19,-0.04"
19,olmo2_unstructured_sparsegpt_0.5_IQ4_XS.gguf.json,0.23,17.31+-0.94,72.56+-4.39,40.48+-5.87,0.30,0.67,"0.01,n=200","-0.15,-0.02"
20,olmo2_unstructured_sparsegpt_0.2_IQ4_XS.gguf.json,0.28,22.80+-1.58,71.91+-4.89,41.40+-6.62,0.20,0.67,"0.00,n=200","-0.20,-0.06"
21,olmo2_unstructured_wanda_0.2_Q8_0.gguf.json,0.28,13.97+-0.85,124.48+-12.71,24.38+-4.09,0.22,0.69,"0.00,n=200","-0.20,-0.06"
22,olmo2_IQ4_XS.gguf.json,0.16,14.64+-0.88,71.44+-4.76,38.36+-5.03,0.59,0.69,"0.64,n=200","-0.08,0.05"
23,olmo2_unstructured_wanda_0.5_IQ4_XS.gguf.json,0.24,18.69+-1.08,71.21+-4.84,40.80+-6.01,0.31,0.71,"0.01,n=200","-0.16,-0.03"
24,olmo2_unstructured_sparsegpt_0.5_Q8_0.gguf.json,0.28,16.69+-0.95,122.38+-13.20,23.55+-2.70,0.22,0.69,"0.00,n=200","-0.20,-0.06"

In [7]:
benchllm.calc_corr(result_df)

,accuracy,ppl,prefill,decode,fail
accuracy,1.00000000000000000000,-0.16330923481015682808,0.03603748475667356566,-0.00596154400760356019,-0.40609140151650124917
ppl,-0.16330923481015682808,1.00000000000000000000,-0.05313132587145032865,0.19299858317697721199,0.31755720063898279504
prefill,0.03603748475667356566,-0.05313132587145032865,1.00000000000000000000,-0.76872987865107467176,0.07577854327597413620
decode,-0.00596154400760356019,0.19299858317697721199,-0.76872987865107467176,1.00000000000000000000,0.36737054663493851070
fail,-0.40609140151650124917,0.31755720063898279504,0.07577854327597413620,0.36737054663493851070,1.00000000000000000000